services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: jp-sims
      POSTGRES_PASSWORD: 3-col-budget-project
      POSTGRES_DB: sims-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local
